development:
  adapter: postgresql
  encoding: unicode
  database: depot_development
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: jdudzik
  password: <% ENV['PG_DATABASE_PASSWORD'] %>
  host: localhost
